### ISSUE TITLE
Hotkeys doesn't work in QT client under Windows

### ISSUE THREAD

**Issue by adkurz** [BearWare/TeamTalk5#1007] opened 2021-09-06 10:58 UTC
I registered a hotkey to enable and disable the voice detection. But it doesn't work. If I press the hotkey, nothing happens. Which hotkey I use, doesn't matters, I tried several hotkeys.
System: Windows 10 21H1 X64, German language, NVDA 2021.2 Beta, Teamtalk QT 5

**Comment by Oreonan** [comment] 2021-09-06 11:09
I think it's a duplicate of #877
Can you confirm that is only hapen with 64 bits (installed) Qt TeamTalk? If you use the portable version this issue is not present?

**Comment by adkurz** [comment] 2021-09-06 11:12
Yes, in the portable version, everything works.

**Comment by Oreonan** [comment] 2021-09-06 11:14
Thanks for confirmed this.
Duplicate of #877

**Closed by Oreonan** 2021-09-06 11:14 UTC

**Comment by bear101** [comment] 2021-09-06 12:04
@Oreonan Sorry if I already asked, but does the 64-bit Classic client have the same issue or is it only appearing in Qt client?

**Comment by Oreonan** [comment] 2021-09-06 15:41
It's apparently only appearing in Qt client, I just tried with an 
installed version of 5.8.1 beta 2 of classic and it works...
