### ISSUE TITLE
Notification sounds are muted whilst connected to a server

### ISSUE THREAD

**Issue by tgeczy** [BearWare/TeamTalk5#164] opened 2016-02-03 15:43 UTC
As submitted by a user:
"when using the team talk app on my iPad air2, i'm unable to hear notification sounds from apps such as twitter or facebook messenger. I'm aware that they sound when using things like skype, just wondering if this could possibley be addressed. Not sure if i'm the only iPad user you have so, hope it helps. :)
from what i've been told, notification sounds work when using the app on iPhones, if that helps some more. :)
"
I don't have an iPad to test this with, but indeed they seem to work on my iPhone as well. Investigating this would be interesting -- is it iPad only or do we need to add some setting for sounds to work when app is open?

**Comment by bear101** [comment] 2017-01-08 12:58
Probably duplicate of #218

**Closed** 2017-09-02 06:49 UTC
Labels: iTeamTalk
