### ISSUE TITLE
Cannot Allow Storage Permition on Android 13

### ISSUE THREAD

**Issue by lbk2907** [BearWare/TeamTalk5#1713] opened 2023-01-15 08:23 UTC
### Description

I was not able to upload/download the file and import the TeamTalk server when using TeamTalk for Android. My current TeamTalk version is 5.12 Build 118. The DLL version is 5.12.0.5104.
My friend told me first that he could not download the file that I uploaded to the channel in my server. He said that that has no way to allow storage permition. Yeah, on Android 13, the storage permition has separate to two that is "music and audio" and "photos and videos".
When I try to clear all data, uninstall TeamTalk and reinstall it, I experience the same. There is know way to allow the storage permition. When I directly log in to my server and download the file, it just said "download files will be unavailable" with not any dialog pops up that will tell me to allow file permition.

### Application

- [ ] qtTeamTalk
- [x] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [x] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

It should able to allow storage permition.

### Actual behavior

Storage permition is missing.

### Steps to reproduce problem

It happend on Android 13. I not sure Android 12 facing the same problem or not.

**Comment by amirmahdifard** [comment] 2023-01-15 09:37
go to app information dialogue, klick on storig, and allow the access from there.

**Comment by lbk2907** [comment] 2023-01-15 09:38
The problem is no storage permition there.

**Comment by bear101** [comment] 2023-01-22 07:28
Duplicate of #1182

**Closed** 2023-01-22 07:29 UTC
Labels: bug, duplicate, TeamTalkAndroid
