### ISSUE TITLE
TeamTalk 5 default QT client, (bug report): Automatically joining root channel upon connection even when this option is unchecked in preferences

### ISSUE THREAD

**Issue by shaghayegh1382** [BearWare/TeamTalk5#1530] opened 2022-10-07 07:48 UTC
### Description

I unchecked "join root channel upon connection" option, but still when I connect to each server, I join root channel automatically. Team Talk version: v5.1.1 (windows)

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

I expect you don't join root channel automatically when you turn off this feature in preferences.

### Actual behavior

You automatically join root channel after connecting to a server even if you disable "join root channel upon connection" in preferences

### Steps to reproduce problem

step 1: I open TeamTalk.
Step 2: I go to preferences.
step 3: I go to connection tab.
step 4: I uncheck "join root channel upon connection"
step 5: I connect to servers.
step 6: Again I join root channel in all servers.

**Comment by amirmahdifard** [comment] 2022-10-07 07:55
are you sure that the admin of the server didn't sighn your user to the root channel?

**Comment by ChrisDuffley** [comment] 2022-10-13 23:13
Cannot reproduce. Can you try closing TeamTalk, reopening it, going to Preferences > Connection and making sure that that checkbox is unchecked before logging onto a server? I've never seen this not work here.

**Comment by bear101** [comment] 2022-10-15 06:24
If a channel is specified in "Connect to a Server" then the client will join that channel despite the "join root channel upon connection"

**Comment by amirmahdifard** [comment] 2022-10-31 17:36
i also canot reproduce with qt client 5.11

**Closed** 2022-11-05 08:56 UTC
Labels: bug, Cannot reproduce
