### ISSUE TITLE
Lost sounds after update to v. 5.12.0.5102

### ISSUE THREAD

**Issue by StormProductionsMusic** [BearWare/TeamTalk5#1595] opened 2022-11-16 11:34 UTC
### Description

Hi there, 

I've just updated to the latest beta version that came up today, amd I lost all the sound events. Even though they are properly set, the volume is at 100, they simply don't play.

Any way to get this fixed?

Thanks.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

The sound events would play after the update.

### Actual behavior

Imediately after update, all the sound events stopped working.

### Steps to reproduce problem

1. Update to the latest beta release (v. 5.12.0.5102)
2. Try doing any action that requires a sound event to play.

**Comment by CoBC** [comment] 2022-11-16 11:46
Duplicate of #1594

**Closed as not planned by CoBC** 2022-11-16 11:46 UTC
Labels: bug, duplicate, qtTeamTalk
