### ISSUE TITLE
TeamTalk Classic crashes when attempting to stream media files.

### ISSUE THREAD

**Issue by slannon97** [BearWare/TeamTalk5#499] opened 2020-04-20 00:15 UTC
The new 5.5 version of TeamTalk 5 Classic crashes when pressing Control+S or selecting the stream media file to channel option in the channels menu. This happens every time a user wants to stream a file.

**Comment by Oreonan** [comment] 2020-04-20 02:32
Allready fixes, duplicate of #491

**Comment by bear101** [comment] 2020-04-20 16:25
Some users have experienced a crash issue using the accessible when trying to open the “Stream Media File” dialog. This issue can be resolved by adding the follow section to TeamTalkClassic.xml between the tag:

<mediafiles>
<last-media-file>foo</last-media-file>
</mediafiles>

Your TeamTalkClassic.xml file is located in
c:\Users\USERNAME\AppData\Roaming\BearWare.dk\

**Closed by bear101** 2020-04-20 16:25 UTC
