### ISSUE TITLE
sound profiles

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#212] opened 2016-07-03 16:35 UTC
sound profiles should be made which will save all possible settings which are linked to sound.

**Comment by bear101** [comment] 2016-08-27 06:22
only thing which left in android audio is the possibility to select
mediarecorder source. i don't know if it is possible to do in java api
now, but i found a possibility how to do it in opensl es.

it is in android configuration file

/*---------------------------------------------------------------------------*/
/* Android AudioRecorder configuration                                       */
/*---------------------------------------------------------------------------*/

/** Audio recording preset */
/** Audio recording preset key */
#define SL_ANDROID_KEY_RECORDING_PRESET ((const SLchar*)
"androidRecordingPreset")
/** Audio recording preset values */
/**   preset "none" cannot be set, it is used to indicate the current settings
 *     do not match any of the presets. */
#define SL_ANDROID_RECORDING_PRESET_NONE                ((SLuint32) 0x00000000)
/**   generic recording configuration on the platform */
#define SL_ANDROID_RECORDING_PRESET_GENERIC             ((SLuint32) 0x00000001)
/**   uses the microphone audio source with the same orientation as the camera
 *     if available, the main device microphone otherwise */
#define SL_ANDROID_RECORDING_PRESET_CAMCORDER           ((SLuint32) 0x00000002)
/**   uses the main microphone tuned for voice recognition */
#define SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION   ((SLuint32) 0x00000003)
/**   uses the main microphone tuned for audio communications */
#define SL_ANDROID_RECORDING_PRESET_VOICE_COMMUNICATION ((SLuint32) 0x00000004)

what do you think, how it should be designed for client application to
select source?

**Comment by bear101** [comment] 2018-10-13 07:03
Duplicate of #119

**Closed by bear101** 2018-10-13 07:03 UTC
Labels: Android, TeamTalk_DLL
