### ISSUE TITLE
bug in qt teamtalk. It's not possible to add a laytist host to the server list with the provided option

### ISSUE THREAD

**Issue by HanaDadfar** [BearWare/TeamTalk5#2351] opened 2024-06-11 09:03 UTC
### Description

When klicking on the add to saved hosts action on the context menu, the view server information dialog appears. But the edit server dialog should appear allowing us to edit the wanted info such as server name and some other info, and then press save and close button to add it to the server list

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

when klicking add to save hosts, the edit server dialog should appear, allowing us to interact with the informations

### Actual behavior

When klicking on add to saved hosts, the view server information dialog appears

### Steps to reproduce problem

press application on a host in the laytist hosts list, and then press enter on add to saved hosts action

**Comment by CoBC** [comment] 2024-06-11 09:08
Can't reproduce

**Comment by HanaDadfar** [comment] 2024-06-11 10:05
ok, I've figgered out the problem, But it's really hard to explane
The problem is that, the add to saved hosts will open the dialog exactly as how last time it was opened, such as edit server or view server, let me explane
0: go to server list table view
1: select an unofficial or official server
2: open context menu and press edit
the view server dialog will open
3: close the dialog, and go to laytist hosts list
4: select a host, open context menu, and press add to saved hosts
the view server dialog will appear
5: Close the dialog, and go to server list table view
6: select a local server, open context menu, and press edit
the edit server dialog will appear
7: close the dialog, and go to laytist hosts list
8: select a host, open context menu, and press add to saved hosts
the edit server dialog will appear
If you follow these steps exactly one by one in your teamtalk, you'll understand what do I mean

**Comment by CoBC** [comment] 2024-06-11 10:22
OK, the issue is when a server is selected in server table view, because we check if selected server from table view is local or not to determine dialog type to display. I'll see

**Comment by CoBC** [comment] 2024-06-11 10:43
Fixed in PR #2352

**Comment by CoBC** [comment] 2024-06-12 06:52
Fixed by #2357

**Closed by CoBC** 2024-06-12 06:52 UTC
Labels: bug, qtTeamTalk
