### ISSUE TITLE
shift + tab bug

### ISSUE THREAD

**Issue by amirmahdifard0** [BearWare/TeamTalk5#936] opened 2021-06-14 02:08 UTC
When using the shift + tab keys to scroll, the focus of the screen reeder has a problem. As you know, with a tab, you get to the speaker adjustment slider. With another tab, you get to the microphone sensitivity adjustment slider. With another tab, you will get a tab that you can switch between files and chats. With another tab, you get to the message history, and with the next tab, you get to where you wrote and sent the message. Now in this section, if you press the tab key once, you will reach the previous place, ie the list of channels. Now in this section too, if you press the shift + tab keys, you will see that the focus is on the chats tab or files tab instead of where the message was written and the message history.

win

classic client for accessibility
5.8.0 beta

**Comment by Oreonan** [comment] 2021-06-14 05:43
Duplicate of #317

**Closed by Oreonan** 2021-06-14 05:43 UTC
