### ISSUE TITLE
Accessibility on Mac

### ISSUE THREAD

**Issue by math65** [BearWare/TeamTalk5#391] opened 2018-11-18 17:28 UTC
Hello,

The mac application has a lot of bugs with VoiceOver. Could you solve them?

Thank

**Comment by bear101** [comment] 2018-11-18 18:29
Unfortunately I don't have the time or resources to improve it.

**Comment by bear101** [comment] 2018-11-18 18:29
Duplicate of #198

**Closed by bear101** 2018-11-18 18:29 UTC
