### ISSUE TITLE
Allow switching Android Team Talk client to mono microphone mode.

### ISSUE THREAD

**Issue by slannon97** [BearWare/TeamTalk5#2179] opened 2024-03-04 14:16 UTC
### Description

Unlike the iOS version, the Android app always uses stereo for the microphones. Please add an option to specify whether the user wants to use mono or stereo for microphone input. Currently, I have to join mono channels if I don't want my voice to pan around the stereo field.

### Application

- [ ] qtTeamTalk
- [X] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkServer

**Comment by bear101** [comment] 2024-03-04 20:47
This seems to be a duplicate of #800

**Closed by bear101** 2024-03-04 20:47 UTC
Labels: enhancement, TeamTalkAndroid
