### ISSUE TITLE
Teamtalk classic cannot switch sound cards in some circumstances

### ISSUE THREAD

**Issue by burakyuksek** [BearWare/TeamTalk5#759] opened 2021-02-12 20:59 UTC
I have a USB headset which I usually use as default sound card. Sometimes this headset stops working so I have to plug it out and plug it back in. When this happens, my voice stops getting transmitted and I cannot hear the other side. I have to restart Teamtalk Classic.

**Comment by MuhammadGagah** [comment] 2021-02-12 23:27
yaps, same problem to me.

**Comment by ChrisDuffley** [comment] 2021-02-13 01:25
This has been in Classic for a long time now. I hope this will be resolved soon.

**Comment by dingpengyu** [comment] 2021-02-15 04:30
cc @bear101

**Comment by bear101** [comment] 2021-02-15 15:57
Duplicate of #712

**Closed by bear101** 2021-02-15 15:57 UTC
