### ISSUE TITLE
iTeamTalk: Master volume no longer functional

### ISSUE THREAD

**Issue by Quartizer** [BearWare/TeamTalk5#153] opened 2016-01-22 21:34 UTC
Master volume slider in preferences defaults to 0 upon connection, but channel participants can still be heard. Moreover, adjusting makes no difference to output volume, and disconnecting and reconnecting causes it to reset to 0.

**Comment by bear101** [comment] 2016-01-23 06:51
I cannot reproduce this problem. What version are you using? You can see the version number in TestFlight

**Comment by Quartizer** [comment] 2016-01-23 10:16
I'm not sure of build number, sorry. I built independently using Xcode yesterday. I hope to be fixing issues soon, not just creating them. :)

**Comment by bear101** [comment] 2016-01-23 13:41
That would be great! Your help will be much appreciated. There's 400 people beta testing iTeamTalk now and they're reporting several issues and MANY feature requests :)

**Comment by bear101** [comment] 2016-01-26 20:33
Closing issue. Reopen if found in 5.1 build 8,

**Closed by bear101** 2016-01-26 20:33 UTC
Labels: bug, iTeamTalk
