### ISSUE TITLE
Implement feature to control audio volume for each user individually by server admins

### ISSUE THREAD

**Issue by shaghayegh1382** [BearWare/TeamTalk5#1830] opened 2023-04-18 05:43 UTC
### Description

Implementing a feature to control audio volume for each user in team talk 5 server config.xml would be a great idea. Such feature already exists in channel properties but it is affective to all users on the channel, but it doesn't let server admins to control audio volume for users individually. Adding this feature will let server admins To prevent users from making too much noise. First, it will be affective in all channels, and it will not change even after logging out. This feature can be available in user accounts dialog, codec limitations section.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [X] TeamTalkServer

**Comment by CoBC** [comment] 2023-04-18 05:59
Duplicate of #1820
As #1820 has moved to a discussion, you can add a comment to indicates that you're intresting for this feature in #1821

**Closed by CoBC** 2023-04-18 05:59 UTC
Labels: duplicate, enhancement

**Comment by shaghayegh1382** [comment] 2023-04-18 08:12
1821 is no longer opened issue. Its closed. Will you attention to
disgussions also?

On 4/18/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
> Duplicate of #1820
> As #1820 has moved to a discussion, you can add a comment to indicates that
> you're intresting for this feature in #1821
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/1830#issuecomment-1512480704
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
Kind regards. You received this email from Abolfazl Saeedifar, you can
simply reply to this message if needed.

**Comment by shaghayegh1382** [comment] 2023-04-19 21:32
Hi, Why you don't attention my request? How much hard is implementing it?

On 4/18/23, Abolfazl Saeedifar ***@***.***> wrote:
> 1821 is no longer opened issue. Its closed. Will you attention to
> disgussions also?
>
> On 4/18/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
>> Duplicate of #1820
>> As #1820 has moved to a discussion, you can add a comment to indicates
>> that
>> you're intresting for this feature in #1821
>>
>> --
>> Reply to this email directly or view it on GitHub:
>> https://github.com/BearWare/TeamTalk5/issues/1830#issuecomment-1512480704
>> You are receiving this because you authored the thread.
>>
>> Message ID: ***@***.***>
>
>
> --
> Kind regards. You received this email from Abolfazl Saeedifar, you can
> simply reply to this message if needed.
>


-- 
Kind regards. You received this email from Abolfazl Saeedifar, you can
simply reply to this message if needed.

**Comment by shaghayegh1382** [comment] 2023-05-06 17:48
Hello. Have you talk to bjon about thr request about control audio
volume for each user?

On 4/20/23, Abolfazl Saeedifar ***@***.***> wrote:
> Hi, Why you don't attention my request? How much hard is implementing it?
>
> On 4/18/23, Abolfazl Saeedifar ***@***.***> wrote:
>> 1821 is no longer opened issue. Its closed. Will you attention to
>> disgussions also?
>>
>> On 4/18/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
>>> Duplicate of #1820
>>> As #1820 has moved to a discussion, you can add a comment to indicates
>>> that
>>> you're intresting for this feature in #1821
>>>
>>> --
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/BearWare/TeamTalk5/issues/1830#issuecomment-1512480704
>>> You are receiving this because you authored the thread.
>>>
>>> Message ID: ***@***.***>
>>
>>
>> --
>> Kind regards. You received this email from Abolfazl Saeedifar, you can
>> simply reply to this message if needed.
>>
>
>
> --
> Kind regards. You received this email from Abolfazl Saeedifar, you can
> simply reply to this message if needed.
>


-- 
Kind regards. You received this email from Abolfazl Saeedifar, you can
simply reply to this message if needed.
