### ISSUE TITLE
TeamTalk 5 Classic: Long recordings become unusable

### ISSUE THREAD

**Issue by winman3000** [BearWare/TeamTalk5#886] opened 2021-05-13 18:11 UTC
## Description

From time to time I like to record TeamTalk conferences as MP3 (128 Kbit/s). The recordings have a length of about 8 hours.

After a while the content of the recording is no longer understandable. It sounds like the recording skips a few seconds or like a CD is skipping. This condition then stays for a few minutes and then returns to normal, but keeps recurring. This problem does not occur immediately. Sometimes it occurs after half an hour, but sometimes it occurs after an hour or two.

If you wish, I can also provide a part of a recording where this problem occurs.

**Comment by bear101** [comment] 2021-05-13 20:06
Please try this version: http://bearware.dk/beta/TeamTalk_v5.8.0.5038_Portable.zip
The single file recording has been completely reimplemented in this version.

**Comment by bear101** [comment] 2021-05-13 20:06
Duplicate of #807

**Closed** 2021-10-30 06:56 UTC
