### ISSUE TITLE
problems in team talk

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1089] opened 2021-11-01 15:40 UTC
Dear bjoern,
I don't like many things about this team talk program and some of these things I have pointed out in previous emails.
For example, in channels even when the option to record voice is disabled, in channels it is always allowed to record even when the storage to disk not allowed option is enabled.
another thing, I don't like that you have decided to put only one server in public servers per country because years ago you could have even more than one server per country.
I have many problems to list but I would also like to tell you about it by talking to you if it is possible.
I have also reported in several messages to put an option that the operator who creates the channel can modify the channel he creates instead of modifying all the channels because that option is already there.
this is a quick rundown on some things I don't like. In other email messages, maybe I'll list others.
regards,
Alessio from Italy.
excuse me for errors the problem is translator.
many years ago you could put many servers per country. I remember in team talk 4 two servers from Usa.

**Comment by bear101** [comment] 2021-11-01 16:29
Isn't this a duplicate of the previous issue you created?

**Closed by bear101** 2021-11-01 16:29 UTC
