### ISSUE TITLE
TeamTalk for Mac, automatic reconnection is slow or fails

### ISSUE THREAD

**Issue by tech10** [BearWare/TeamTalk5#325] opened 2017-11-07 18:49 UTC
If the connection to the TeamTalk server is dropped for any reason, reconnecting automatically is slow if the connection drops and is able to return right away, and can fail if the server is down for longer than a few seconds. If using multiple instances of TeamTalk, automatically reconnecting to the servers fails completely.

**Comment by bear101** [comment] 2018-05-07 05:26
Is this also fixed in this version? http://bearware.dk/beta/TeamTalk_v5.3.2.4928_Setup.dmg

**Comment by tech10** [comment] 2018-05-07 11:12
Nope, the same thing still happens.

**Comment by bear101** [comment] 2018-10-13 06:45
Is there a way to reproduce this issue otherwise I'll close it

**Comment by tech10** [comment] 2018-10-13 09:53
Launch one or more copies of TeamTalk connected to external servers, then either disconnect the computer from the network or stop the servers. Leave the servers inaccessible to the connecting clients for at least a minute, then reestablish the connection to the servers by bringing them back up, or connecting the connecting computer back to the network. Watch what happens. Compared to the classic TeamTalk client, the one for Mac OS has issues with this reconnection. There have been times where I've lost connection to my servers for a moment, only to have the client sit there in a locked state, unable to reconnect until I manually intervene. Also, the CPU use can go up when the clients or client is trying and failing to reconnect to the server, and whenever I've used multiple instances, automatically reconnecting to the servers does seem to fail completely.

**Comment by bear101** [comment] 2020-05-09 06:59
I have two macOS PC's and cannot reproduce the issue

**Closed by bear101** 2020-05-09 06:59 UTC
