### ISSUE TITLE
More options in classroom wanted

### ISSUE THREAD

**Issue by BrianOlesen02** [BearWare/TeamTalk5#746] opened 2021-01-28 07:57 UTC
### this isn't a real issue, but more of a good idea.
I would like to see a more easy to use classroom interface that also works with mobile phones. I mean in these Corona times it would be nice to use TeamTalk in large groupe discussions.

**Comment by tbdalgaard** [comment] 2021-04-12 19:25
@BrianOlesen02 which features are you thinking of specifically? Your idea sounds interesting, but how can @bear101 do something without having a clue what you are looking for?

**Comment by bear101** [comment] 2021-12-08 05:53
Duplicate of #361

**Closed by bear101** 2021-12-08 05:53 UTC

**Comment by BrianOlesen02** [comment] 2022-03-17 21:31
Hejsa

Blindkom.dk kører en relativt ny server 5.8x og mine klienter kører med
seneste udgave fra AppStore.

Men folk kan ikke komme ind i password-beskyttede kanaler, hvis de bruger
VoiceOver.

 

Sig til, hvis du behøver mere info.

Mvh. Brian
