### ISSUE TITLE
Webcam for Linux client

### ISSUE THREAD

**Issue by sp2ong** [BearWare/TeamTalk5#111] opened 2015-11-15 11:50 UTC
I have try use TT5.1.1 under Ubuntu Linux with my integrated laptop webcam but I can not see possibility to select this cam in option TT. TT client under linux support webcams ???

Regards

**Comment by bear101** [comment] 2015-11-17 07:56
Duplicate of #41

**Closed by bear101** 2015-11-17 07:56 UTC
