### ISSUE TITLE
Allow More Audio Apps to Function Alongside iTeamTalk

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#977] opened 2021-07-25 22:22 UTC
Since the release of TeamTalk for iOS, most other apps that play audio have caused TeamTalk to stop transmitting and receiving audio. When TeamTalk recovers, it doesn't reinitialize the microphone, only the receiving side. This means that if a user opens any audio playback (including unintentionally clicking a video on social media, for instance), they will almost certainly need to close and reopen TeamTalk. While fixing the bug with microphone initialization is a partial solution, I'm very interested in seeing support for TeamTalk and other audio apps to play simultaneously. Here's a non-exhaustive list of things I can't do on my iPhone while connected to a server, some less obvious than others:

* Use the Spotify app to control playback on other devices
* Play YouTube videos, Spotify, etc.
* Launch a website with a video that autoplays, even if the video starts muted
* Use most blind-friendly GPS apps such as Microsoft Soundscape (either because they play audio to represent places or because they use Apple's built-in TTS)
* Listen to audio books or podcasts
* Read books using any app that uses Apple's built-in TTS

I would love to get to a point where I can keep TeamTalk loaded but still accomplish other audio-related tasks on my phone or iPad. While I don't know for certain that this is possible, I have seen two apps function in a similar way. One is an older version of TeamSpeak; the other is Clubhouse. (And while Clubhouse doesn't have stereo audio, I believe that's by design.)

I would even be willing to give up stereo audio as a user preference if it meant being able to use other audio apps. But I don't believe that would be necessary.

The only other consideration is that headset TX control wouldn't function properly while another app is taking over those controls, but I think this would be acceptable as well.

**Comment by bear101** [comment] 2021-07-27 16:43
Hi Simon. This is actually a duplicate of #218. From the little research I've done so far there doesn't seem to be a simple way to fix this.

If anyone has some clues then I can try to implement the required changes.

-- Bjørn

**Comment by Simon818** [comment] 2021-07-27 16:49
I remember all my childhood phone numbers, but I apparently don't remember making the first issue. Sorry for the duplicate. I wish I had suggestions for how this can be done, but I know it *is* possible. Other than Clubhouse, there are apps like Nature Space that can play audio in the background while still allowing you to play music (or, incidentally, use TeamTalk). I don't have solid data on how any of that is being done though.

**Comment by bear101** [comment] 2021-11-12 06:14
I've submitted v5.8.3 build 1 which allows TeamTalk to run while e.g. YouTube is playing.

**Comment by Simon818** [comment] 2021-11-12 06:18
@bear101 That is intriguing; I'm really looking forward to that, and I appreciate the (probably significant) work that went into that. I'll comment here with findings.

**Comment by Simon818** [comment] 2021-11-13 00:20
This seems to work really well. I'm curious what you're doing to achieve this, because I notice that on Clubhouse and now on this new TeamTalk beta, I can't hear notification sounds anymore. This is something I'd like to report to Apple if possible. Anyway, thank you for taking this seriously. This is an enormously helpful improvement.

**Comment by bear101** [comment] 2021-12-02 20:42
Currently the sound input device is not remembered during sessions. I'll fix this later.

**Closed** 2021-12-02 20:41 UTC
Labels: iOS, iTeamTalk
