### ISSUE TITLE
streaming Mediafiles for long time - TT5Classic

### ISSUE THREAD

**Issue by wandogau** [BearWare/TeamTalk5#671] opened 2020-09-30 13:39 UTC
Situation: we have some channels, where we want to have some background noise.
So I created 3 users, one for each of these channels, with Admin-Account and let each user stream a media file continously. Each user runs in a TT-instance.
All works fine, but after a while I get the error 
command overflow
and the media file stopps working.
This can happen after two hours, or after two days - no chance to reproduce it.
The PC runs of course W10 and the latest TT5Classic 5.6.3.
Flood-protection is off, as always with admin-accounts.

**Comment by bear101** [comment] 2020-09-30 17:05
Flood protection is tied to the user account. Also admin user accounts.

Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by wandogau** [comment] 2020-09-30 18:22
Yes, but it‘s turned off.

 

 

Von: Bjørn Damstedt Rasmussen <notifications@github.com> 
Gesendet: Mittwoch, 30. September 2020 19:06
An: BearWare/TeamTalk5 <TeamTalk5@noreply.github.com>
Cc: wandogau <info@l-becker.de>; Author <author@noreply.github.com>
Betreff: Re: [BearWare/TeamTalk5] streaming Mediafiles for long time - TT5Classic (#671)

 

Flood protection is tied to the user account. Also admin user accounts.

Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by bear101** [comment] 2020-12-31 05:37
I cannot reproduce the issue so closing. Reopen if there a reliable way of reproducing.

**Closed by bear101** 2020-12-31 05:37 UTC
