### ISSUE TITLE
Teamtalk5 mac  treeview accessibility

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#103] opened 2015-08-24 15:58 UTC
hello bjoern.

as we all know, treeview in mac is not accessible for blind users.

i suggest making not such an elegant thing but it will fix accessibility problem.

make one more menu group with server name in mac version, in which channels will be located as menu items and users if they are in channels submenus.

i know that approach has some side effects but i think this will be better than nothing.

what do you think about that?

**Comment by bear101** [comment] 2017-09-09 07:37
Duplicate of #198

**Closed by bear101** 2017-09-09 07:37 UTC
Labels: qtTeamTalk
