### ISSUE TITLE
QT Teamtalk can't connect to last server in second profile

### ISSUE THREAD

**Issue by grishakonzalaev** [BearWare/TeamTalk5#1297] opened 2022-04-07 14:00 UTC
### Description

I create and preference second profile. I check last server connection checkbox in connection tab.
Then I go to any server. Then Close profile.
Reopen again. Profile starts, but no connection to last server.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

When I open customized profile, connection to last server must be established.

### Actual behavior

When I open customized profile, no connection to server.

### Steps to reproduce problem

1. create profile.
2. preferences in created profile: check last server connection checkbox on connection tab.
3. connect to server with this profile.
4. close this profile and reopen it.

**Comment by bear101** [comment] 2022-07-20 06:17
Caused by: https://github.com/BearWare/TeamTalk5/blob/master/Client/qtTeamTalk/mainwindow.cpp#L3924

Not really sure why "noconnect" is a default argument to the new instance.

**Comment by CoBC** [comment] 2022-07-30 20:54
The only reason I can see is to avoid connection to multiple servers at the mean time. A solution can be to add "noconnect" arg only if first instance is already connected.

**Comment by bear101** [comment] 2022-08-03 07:25
Artifacts from this workflow has the feature: https://github.com/BearWare/TeamTalk5/actions/runs/2787629569

**Comment by bear101** [comment] 2022-08-13 06:21
Closing issue. Please try artifacts from master builds: https://github.com/BearWare/TeamTalk5/actions/workflows/windows.yml?query=branch%3Amaster

Reopen if it's still an issue.

**Closed by bear101** 2022-08-13 06:21 UTC
Labels: bug, qtTeamTalk
