### ISSUE TITLE
Text to Speech support for common events (Siri?)

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#137] opened 2016-01-05 21:17 UTC

**Comment by beqabeqa473** [comment] 2016-01-06 14:48
hi bjoern.

import AVFoundation

let synth = AVSpeechSynthesizer()
var myUtterance = AVSpeechUtterance(string: "")

//initializes tts engine.


//when triggering an event.
myUtterance = AVSpeechUtterance(string: event)
synth.speakUtterance(myUtterance)


something similar.

i wanted to implement such thing but i don't have a device to build and test, so i didn't commit untested things.

**Comment by bear101** [comment] 2016-01-10 07:53
James Walton:
Very nice so far! It would be nice if you could have voiceover announce as messages came in in private messages and in the messages tab.

**Comment by bear101** [comment] 2016-01-10 07:53
Say message and from, not time-stamp

**Comment by bear101** [comment] 2016-01-10 07:57
Make Siri/VoiceOver sestion in preferences. Make checkboxes for every type of announcement.
Join
Left
Logged on
Incoming message
Kicked
Lost connection

**Comment by beqabeqa473** [comment] 2016-01-10 16:40
hi bjoern.

an initial implementation was pushed.
please look at it.

**Comment by bear101** [comment] 2016-01-10 17:24
It works! It, however, needs to be translated. Please check out how NSLocalizedString is being used. Also there's a space missing between nickname and following word.

**Comment by bear101** [comment] 2016-01-10 17:40
The utterances that is. The preference items are ok.

**Comment by beqabeqa473** [comment] 2016-01-10 17:45
i have one issue.

when installing teamtalk first time, values aren't stored, i need to toggle switches.
do you have such problem?
if yes, can you point me at the right direction?

**Comment by beqabeqa473** [comment] 2016-01-10 18:04
fixed comment reports.

**Comment by bear101** [comment] 2016-01-11 07:14
I do like this when reading from preferences the first time:
```
 if defaults.objectForKey(PREF_VOICEACTIVATION) != nil {
            let voiceact = defaults.integerForKey(PREF_VOICEACTIVATION)
```

**Comment by bear101** [comment] 2016-01-11 16:19
I'll fix the initial values for TTS preferences

**Comment by beqabeqa473** [comment] 2016-01-12 06:03
thank you bjoern.
so, now rate, volume and pitch should be added to settings.
do you agree with that?

**Comment by tgeczy** [comment] 2016-01-12 06:42
It should be pointed out that if one goes to settings, general, accessibility, and speech, they can adjust the rate systemwide. In fact, this is how a person can choose a new or different voice. This is a universal setting, which sets default values for any TTS events.

**Comment by tgeczy** [comment] 2016-01-17 16:58
I have conflicting reports on whether General > accessibility > Speech changes the rate or not that iTeamTalk speaks with.
Implementing rate change is more trivial than I expected though. Below is a sample of how I did it in PreferencesView Controler. Bjoern, do you know how we can assign the float value to myUtterance.rate? Some examples do this by creating a preferencesViewControler delegate and using that as a bridge between the values. The problem is that PREF_TTSEVENT_RATE is stored as a string. Converting it to a float will cause the app to crash when you set myUtterance.rate to the converted value.
The below code works to store and retrieve the rate values at least.

let PREF_TTSEVENT_RATE = ""
var ttsratecell : UITableViewCell?
        ttsratecell = UITableViewCell(style: .Subtitle, reuseIdentifier: nil)
        var ttsrate = DEFAULT_TTS_RATE
        if settings.valueForKey(PREF_TTSEVENT_RATE) != nil {
            ttsrate = settings.floatForKey(PREF_TTSEVENT_RATE)
        }
let ttsrateslider = newTableCellSlider(ttsratecell!, label: NSLocalizedString("TTS Rate", comment: "preferences"),
            min: 0, max: 1, initial: Float(ttsrate))
        ttsrateslider.addTarget(self, action: "ttsrateChanged:", forControlEvents: .ValueChanged)
        ttsrateChanged(ttsrateslider)
        ttsevents_items.append(ttsratecell!)

func ttsrateChanged(sender: UISlider) {
        let defaults = NSUserDefaults.standardUserDefaults()
        defaults.setFloat(Float(sender.value), forKey: PREF_TTSEVENT_RATE)
        let txt = String(format: NSLocalizedString("The rate of the speaking voice is %.1f", comment: "preferences"), Float(sender.value))
        ttsratecell!.detailTextLabel!.text = txt
            }

**Comment by bear101** [comment] 2016-01-18 20:41
So it's when you change ```AVSpeechUtterance.rate``` that it crashes when you call ```synth.speakUtterance(myUtterance)```?

**Comment by tgeczy** [comment] 2016-01-18 21:19
No. The problem is that the value of PREF_TTSEVENT_RATE is stored
inside of a string, not a float value. When you convert from float to
string
var myUtterance.rate = ( as NSString).floatValue, .
If you converted that preferences string or somehow tried to extract
the value out of that preferences string thinking it could easily turn
into the proper Float, it doesn't actually convert it.
 You also can't pass the stepper to the myutterance.rate function,
because the stepper passes its value as a double, not as a float.
(though the easiest way for the rate slider to work would be to have
it pass the sender.value to the speech rate as a float.)
-Tamas

**Comment by bear101** [comment] 2016-01-18 21:21
Hm ok. I can look at it tomorrow. Maybe you can create a branch and commit the code you have now.

**Comment by tgeczy** [comment] 2016-01-18 22:07
I could, if that'd make things easier. I'll also add volume into
settings alongside rate, as people say the TTS is too loud compared to
the channel.
Hope Denmark's a bit warmer than us -- -15C here! :D
Sincerely,
Tamas

**Comment by bear101** [comment] 2016-01-19 17:12
I'm looking at the code now and making a few changes to simplify TTS.

It's "only" -7C here, so it's not too bad. I'm cycling 15 km to work every day so I just dress appropriately :)

**Comment by tgeczy** [comment] 2016-01-19 17:25
Thanks Bjoern. I added both rate / volume for
PreferencesViewController, but both are the same format:
myUtterance.rate and myUtterance.volume need a float value from 0.0 to
1.0.
In one code example, I saw this done by making a protocol, then
delegate of PreferencesViewControler in ChannelListViewController, but
doing that seems super complex and almost redundant for such a simple
feature. If this were a purely tts-focused app, that would make more
sense, like the example. Here's a link to it though:
http://www.appcoda.com/text-to-speech-ios-tutorial/

I have a twin sister in Copenhagen doing her neuroscience program
there, so I know how big bicycles are over there. That's a good
workout for sure!
Sincerely,
Tamas

**Comment by bear101** [comment] 2016-01-19 17:29
Yes, we love bikes :)

I've submitted the TTS fix and made a few adjustments. If you want to continue working on this branch then please do and just let me know when I should merge the changes to the master branch. Or you can do it yourself if you're a Git expert.

**Comment by bear101** [comment] 2016-01-19 17:37
Btw, someone asked if it was possible to change the voice of the speaker to "Alex". Do you if there's an easy way or is it something that can already be done in General > Preferences.

**Comment by tgeczy** [comment] 2016-01-19 17:44
Hi Bjoern,
There's a way to query the list of voices, it's demoed in the example
actually. I can add that later this afternoon using the examples there
hopefully.
One more option I'll probably add is just a simple "test speech"
button, which is also easy to do at the end of the TTS events
settings. Then I think we'll have a complete implementation for the
feature.
By the way, if we still need French translations, I have several
people who have interest in translating. Let me know if I should give
them a blank template for strings.
-Tamas

**Comment by beqabeqa473** [comment] 2016-01-19 17:49
hi all.

as for changing voice to alex, we need multilinguality and alex doesn't support it.

**Comment by tgeczy** [comment] 2016-01-19 17:55
I think that whatever you set the default voice to in settings >
general >accessibility will adjust it, but again I'm not sure.
It's possible to query all languages and voices to build a list and
use that instead. For now, if a person sets his or her system language
and locale to something different (E. Danish), the voice will
automatically change to that region as well. In General >accessibility
> speech, you can manually change what voice you want for what
dialect. For that reason I don't know if a manual way of changing
voice specific to iTeamTalk is needed, because the localization and OS
will take care of it. Still, let me know what you guys think.
 Experiment by going into general > accessibility and see if the
iTeamTalk voice changes depending on what you set there. Change your
language to a different one in settings > general > language and
region, and the announcements should change along with the voice that
is assigned to that language.

**Comment by tech10** [comment] 2016-01-19 17:58
Hi,
I've attempted to change the voice in the speech accessibility settings to the male voice, as I use that one with Siri, so wanted to use it with TeamTalk as well. It didn't seem to change what voice was used for text to speech. Changing the rate also had no effect.

I don't know if this would be possible, but perhaps VoiceOver could be used to speak text to speech events as well. This would probably be best to limit that to when the iTeamTalk application is active.

Blake

**Comment by tgeczy** [comment] 2016-01-19 18:22
Hi Blake,
Yes. I just tried changing it and it seems to be a hit or miss. At one
point me messing with rate did lower it, but changing the voice to
Alex kept it at Samantha compact. Very weird if I must say so, you'd
think the function would have defaults that the user can specify and
that's why Apple made that section in settings.
I'll add the picker item to settings with all available voices / languages. :)
I think that making it VoiceOver only for announcement would be a bit
too exclusive. I can see the feature being used by non-blind people as
well (so the sighted world using iTeamTalk), especially if you're
elsewhere in iOS and need to know who joined the channel. At that
point we might as well make it a push  notification, but having TTS
read it automatically is much nicer and well worth the effort that it
needs. :)
-Tamas

**Comment by bear101** [comment] 2016-01-19 18:36
@tgeczy if you can get other people to translate the program then please do. Also the French version!
A guy from Estonia contacted me so it should be on the way already.

**Comment by bear101** [comment] 2016-01-21 21:32
@tgeczy the voice you enumerate are voices for countries. Shouldn't it be person's voice (Samantha or Alex)?
I've added the picker-view to a cell but it causes all cells to grow in height. I have to figure out why they do this.

**Comment by tgeczy** [comment] 2016-01-21 22:41
Sadly we can't choose based on person alone. The method only returns
all voices as language codes. It's possible that the list will include
various voices for languages, though, such as male / female ones. I
don't know what the dictionary will return exactly, but seeing them in
a picker would help.
-Tamas

**Comment by bear101** [comment] 2016-01-26 19:13
Feedback from Andre Louis:
Only thing if possible, make the TTS speak a little test text when you make a change, so you know what it will sound like in a real situation.
I had to join another channel to hear what my changes would sound like. Just a thought.
No crashes as yet, but only been testing for 5 minutes.

**Comment by tgeczy** [comment] 2016-01-26 19:50
Hi Bjoern,
I have this already in the SpeechControl branch. The problem I faced
was connecting the "test" button in with the main storyboard. There
are both the IBAction and IBOutlet for the button, could you possibly
drag it to the storyboard to connect it?
I tried to do it with VoiceOver but for some reason dragging the
button from one pain to the storyboard did nothing. :(
-Tamas

**Comment by bear101** [comment] 2016-01-26 19:52
Ok, I can look at it.

I've asked my wife to do the French translation, so it should be 
available soon.

Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by bear101** [comment] 2016-01-27 19:30
I've figured out how to change the voice, so I'll look at that now.

**Closed** 2016-01-30 21:33 UTC
Labels: enhancement, iTeamTalk

**Comment by marsp61** [comment] 2022-08-01 07:58
Fixed the problem with Siri and the Error: "Es ist ein Fehler aufgetreten, versuchen Sie es zu einem späteren Zeitpunkt erneut" by installing iOS Beta 4 - but still I don't get the subtitles off. They show up anyway. It doesn't matter if the 
level is "ON", or "OFF". What might be the problem.
