### ISSUE TITLE
system lag after lost teamtalk connection

### ISSUE THREAD

**Issue by jeremyp3** [BearWare/TeamTalk5#791] opened 2021-03-02 21:32 UTC
Hello,

I tested on the qt client (linux) and the classic client (windows). as soon as teamtalk tries to reconnect after losing the connection, it makes the system lag and suddenly it slows down the screen reader.

would it be possible to correct this bug?

thanks,

Jeremyp3

**Comment by bear101** [comment] 2021-04-05 17:07
What client version is this?

**Comment by jeremyp3** [comment] 2021-04-05 17:11
currently I use 5.7 under linux but I reproduced this for many versions
back

**Comment by Simon818** [comment] 2021-04-13 22:38
Can confirm this has happened for quite some time, but I think it got worse in 5.7. I have a few instances of TeamTalk open on my server to shuffle audio here and there, and if my internet or the relay server goes down, my system slows to a crawl. I've occasionally found that one or two of the instances go unresponsive if the server is down for a long time. Whatever it's doing while trying to reconnect seems to be key.

**Comment by bear101** [comment] 2021-05-01 05:48
@Oreonan I've heard this from other users as well. Do you have any idea how to reproduce this? Could it be the screen-reader interface that gets screwed up?

**Comment by Oreonan** [comment] 2021-05-01 06:06
To reproduce it, you have to cause a loss of connection when the 
TeamTalk interface is in the foreground. When TeamTalk tries to 
reestablish the connection, the screen reader freezes. I think it's only 
the screen reader that freezes and not the system, because if we try, 
for example in Windows, to go to the desktop and type a letter with 
which nothing starts, the default sound is played well by the system.

**Comment by bear101** [comment] 2021-05-01 06:09
Ok, so it's if the TeamTalk client is blocking during TT_Connect()?

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by Oreonan** [comment] 2021-05-01 06:11
Yes, exactly.

**Comment by bear101** [comment] 2021-05-01 06:17
Ok, this is an inherent problem in inet_pton
<https://linux.die.net/man/3/inet_pton>. The solution is to use
IP-addresses instead of host names.

Note, however, that TeamTalk encrypted servers use a blocking connect so
even using an IP-address will not solve the issue there.

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by jeremyp3** [comment] 2021-05-01 06:57
it is not possible to use another way to connect using a library which
will not pose this problem? I guess that would mean rewriting the whole
connection part, that must be a lot of work

**Comment by bear101** [comment] 2021-07-14 20:15
Closing issue due to inherited problem in inet_pton

**Closed by bear101** 2021-07-14 20:15 UTC
